### ISSUE TITLE
milestones part

### ISSUE THREAD

**Issue by palabhi017** [palabhi017/terrific-language-9890#60]
- [x] main heading
- [x] create different boxes
- [x] adding image in the box
- [x] adding date, description, heading
